name: Periodic Health Check

on:
    push:
        branches:
        - main
    schedule:
    - cron: '0 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Perform Health Check
        uses: jtalk/url-health-check-action@v4
        with:
          url: 'https://full-stack-open-pokedex-tk93.onrender.com/health'
          max-attempts: 3
