name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install  

      - name: Check style
        run: npm run eslint
    
      - name: Build
        run: npm run build

      - name: Notify Failure
        if: ${{ failure() }}
        uses: stegzilla/discord-notify@v2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            **Build failed!**
            Commit ${{ github.sha }} broke the build

      - name: Run tests
        run: npm run test

      - name: Install Playwright
        run: npx playwright install

      - name: Run Playwright Tests
        run: npm run test:e2e
    
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' &&  !contains(github.event.head_commit.message, '#skip') }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

      - name: Notify Success
        if: ${{ success() }}
        uses: stegzilla/discord-notify@v2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            **Deployment succeeded!**
            A new version of Pokedex deployed!
  

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' &&  !contains(github.event.head_commit.message, '#skip') }}
        uses: anothrNick/github-tag-action@1.71.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch